export enum USER_ACTION_TYPES {
    FETCH_USER = 'FETCH_USER',
    FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED',
    LOGIN_USER = 'LOGIN_USER',
    REGISTER_USER = 'REGISTER_USER',
}
// export const FETCH_USER = 'FETCH_USER'
// export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED'