export enum USER_ACTION_TYPES {
    FETCH_USER = 'FETCH_USER',
    FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED',
}
export const ADDTODO = 'ADDTODO';
export const ADDONE = 'ADDONE';
// export const FETCH_USER = 'FETCH_USER'
// export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED'